### ISSUE TITLE
[Question] On the error bound of the Walk-SAT algorithm.

### ISSUE THREAD

**Issue by prime235711** [hongseok-yang/logic23#1]
This is a question about the lecture.
At the last page of the lecture, you said that repeating the $m$ phases of probability $\frac12$ events makes the error bound $2^{-m}$.
But I think this is possible only if the events are all independent. 

Iterativly applying the Markov's inequality needs some assumption like $$\mathbb{E}[X|X\ge n^2]\le 2n^2$$ but it doesn't seem obvious to me.
Can you give me some more clarification about this?

**Comment by hongseok-yang** [comment]
Very good. Indeed, the precise statement should use conditioning. Concretely, we first note that

P(X >= 2mn^2)
\eq 
P(X >= 2n^2) x P(X >= 4n^2 | X >= 2n^2) x ... x P(X >= 2mn^2 | X >= 2(m-1)n^2).

Then, we show that

P(X >= 2kn^2 | X >= 2(k-1)n^2) <= 1/2

using Markov's inequality for the conditioned random variable X. That is,

P(X >= 2kn^2 | X >= 2(k-1)n^2) 
\eq
P((X - 2(k-1)n^2) >= 2n^2 | X >= 2(k-1)n^2)
<= 
E[(X - 2(k-1)n^2) >= 2n^2 | X >= 2(k-1)n^2] / 2n^2   
<=  -- (**)
T_n / 2n^2
<=
H_n / 2n^2 
\eq
n^2 / 2n^2 
\eq
1/2

The (**) step uses

E[(X - 2(k-1)n^2) >= 2n^2 | X >= 2(k-1)n^2] 
<=
T_n

which I think can be shown by doing (probabilistic) case analysis on the assignment B that the algorithm reaches after the 2(k-1)n^2 iterations.

Best wishes,
Hongseok
