### ISSUE TITLE
[Question] About the use of ChatGPT or related technology.

### ISSUE THREAD

**Issue by doehyunbaek** [hongseok-yang/logic23#2]
Hi professor. It is always a great pleasure listening to the lectures and doing the required assignments.

To what extent is the use of language models like ChatGPT allowed in solving programming assignment or homework assignment? It seems they are pretty proficient in solving the problems like dpll. 

Also, to what extent AI-based code assist tools like Github Copilot is allowed when doing assignments?

Thank you again for you great lecture.

Doehyun Baek

**Comment by hongseok-yang** [comment]
For this semester, we do not allow students to use ChatGPT or AI-based tools for solving homework questions and doing the programming project.

**Comment by doehyunbaek** [comment]
Thanks for the quick answer. Closing this issue.
