### ISSUE TITLE
[Question] Programming assignment python version

### ISSUE THREAD

**Issue by p51lee** [hongseok-yang/logic23#3]
Exactly which version of Python is used to evaluate the programming assignment?
I wonder how much I can take advantage of the new features in Python 3.8, 3.9, and 3.10.

**Comment by mekty2012** [comment]
You may use any features from those versions, but not 3.11.
We will evaluate your score on most recent version that your code do not make error, which I believe 3.10 will work for every submission thanks to backward compatibility.

**Comment by p51lee** [comment]
Thank you for your response.
