### ISSUE TITLE
[Question] Minor error on the lecture note

### ISSUE THREAD

**Issue by doehyunbaek** [hongseok-yang/logic23#4]
[In this lecture note](https://github.com/hongseok-yang/logic23/blob/main/Notes/lecture8-notes.pdf), page 4, figure 2, it says

> Automaton accepting all strings in which each q is followed by some p

Isn't it `in which each p is followed by some q`? 

If not, sorry for the confusion on my side.

**Comment by mekty2012** [comment]
"모든 p...p 다음에 q가 오는 문자열" 입니다.

For example, you can think of 
''
'pq'
'pqqq'
'pqpq'
'pppq'
that will be accepted, but not
'p'
'ppp'
'pqppp'
accepted.

By the way, if you check the course syllabus, we are using KLMS as a tool for course discussion. Please refrain from using github issue for the question. It will make other students to check both side.

**Comment by doehyunbaek** [comment]
Sorry for not following instructions.

Closing and will post on KLMS if there are further questions.

**Comment by mekty2012** [comment]
@doehyunbaek  
There were miss in the answer, I wrote converse for p and q. Since I edited the answer, please check it again.
