### ISSUE TITLE
Using external python libraries for SAT solver

### ISSUE THREAD

**Issue by YoungseokCh** [hongseok-yang/logic23#5]
In README.md, it says that we cannot use any libraries 'directly related' to SAT solving.

> Your implementation should not use any external python libraries directly related to SAT solving.

Can I use packages such as numpy to improve the performance? I wonder is it violating the homework instruction.

**Comment by mekty2012** [comment]
Yes, you can.

In terms of python libraries directly related to SAT solving, we are saying libraries like Py-SAT or Z3Py, those that gives solution directly.
